os: linux
  
language: go

go:
  - 1.13.x

services:
  - docker

script:
  - go test -v ./...
  - CGO_ENABLED=0 go build -o demo
  
  - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
  - docker build -f Dockerfile -t nhoelzl/demo:latest ./

  - GIT_SHA="$(git rev-parse --short HEAD)"
  - docker tag nhoelzl/demo:latest nhoelzl/demo:$GIT_SHA

  # push images to docker hub
  - docker push nhoelzl/demo:latest
  - docker push nhoelzl/demo:$GIT_SHA